chore(linux) factorize JDK specification to docker bakefile
Signed-off-by: Damien Duportal <damien.duportal@gmail.com>

diff --git a/debian/Dockerfile b/debian/Dockerfile
--- a/debian/Dockerfile
+++ b/debian/Dockerfile
@@ -1,13 +1,36 @@
-FROM eclipse-temurin:17.0.7_7-jdk-focal as jre-build
+ARG JAVA_VERSION=17.0.7_7
+FROM eclipse-temurin:"${JAVA_VERSION}"-jdk-focal AS jre-build
+
+# This Build ARG is populated by Docker
+# Ref. https://docs.docker.com/engine/reference/builder/#automatic-platform-args-in-the-global-scope
+ARG TARGETPLATFORM
+
+SHELL ["/bin/bash","-e", "-u", "-o", "pipefail", "-c"]
 
 # Generate smaller java runtime without unneeded files
 # for now we include the full module path to maintain compatibility
-# while still saving space
-RUN jlink \
-         --add-modules ALL-MODULE-PATH \
-         --no-man-pages \
-         --compress=2 \
-         --output /javaruntime
+# while still saving space (approx 200mb from the full distribution)
+RUN if test "${TARGETPLATFORM}" != 'linux/arm/v7'; then \
+    case "$(jlink --version 2>/dev/null)" in \
+        # jlink version 11 has less features than JDK17+
+        "11."*) strip_java_debug_flags=("--strip-debug") ;; \
+        *) strip_java_debug_flags=("--strip-java-debug-attributes") ;; \
+    esac; \
+    if test "${TARGETPLATFORM}" != 'linux/amd/64'; then \
+        # posix_spawn (default for JDK12+) fails erratically with qemu on non x86 CPUs - https://github.com/openzipkin/docker-java/issues/34#issuecomment-721673618
+        export JAVA_TOOL_OPTIONS='-Djdk.lang.Process.launchMechanism=vfork'; \
+    fi; \
+    jlink \
+        --add-modules ALL-MODULE-PATH \
+        "${strip_java_debug_flags[@]}" \
+        --no-man-pages \
+        --no-header-files \
+        --compress=2 \
+        --output /javaruntime; \
+    # It is acceptable to have a larger image in arm/v7 (arm 32 bits) environment.
+    # Because jlink fails with the error "jmods: Value too large for defined data type" error.
+    else cp -r /opt/java/openjdk /javaruntime; \
+    fi
 
 FROM debian:bullseye-20230502
 
@@ -31,11 +54,11 @@ RUN groupadd -g ${gid} ${group} \
 
 RUN apt-get update \
     && apt-get install --no-install-recommends -y \
-       git-lfs \
-       less \
-       netcat-traditional \
-       openssh-server \
-       patch \
+        git-lfs \
+        less \
+        netcat-traditional \
+        openssh-server \
+        patch \
     && rm -rf /var/lib/apt/lists/*
 
 # setup SSH server
